question_data = [
    {"category": "Entertainment: Music",
     "type": "boolean", "difficulty": "medium",
     "question": "Ashley Frangipane performs under the stage name Halsey.", "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "Tennis was once known as Racquetball.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium", "question": "The Platypus is a mammal.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Oxford University is older than the Aztec Empire. ", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Sports", "type": "boolean", "difficulty": "medium",
                                       "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Nick Mason is the only member to appear on every Pink Floyd album.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "Is Tartu the capital of Estonia?",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
